export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Info } from './Info/Info'
export { default as Myths } from './Myths/Myths'
export { default as Settings } from './Settings/Settings'
export { default as Stats } from './Stats/Stats'
export { default as Details } from './Stats/Details/Details'